name: time_parser
description: parses a time string and returns a time object in order to easily access hours and minutes.
version: 1.1.0

homepage: https://github.com/AndreeWille/time_parser
repository: https://github.com/AndreeWille/time_parser
issue_tracker: https://github.com/AndreeWille/time_parser/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
